# Generated by Django 5.2.6 on 2025-09-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('super', 'Superusuario'), ('artist', 'Artista'), ('space', 'Espacio cultural'), ('collaborator', 'Colaborador'), ('evento', 'Evento')], default='artist', max_length=20),
        ),
    ]
