# Generated by Django 5.2.6 on 2025-09-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_expense_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categoria_arte',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='codigo_promocion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='comentario_novedades',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
        migrations.AddField(
            model_name='event',
            name='horario',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='pais',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='porcentaje_descuento',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
