# Generated by Django 5.2.6 on 2025-09-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_categoria_arte_event_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fecha_publicacion_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='fecha_publicacion_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
