# Generated by Django 5.2.6 on 2025-09-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='espacios/'),
        ),
    ]
