# Generated by Django 5.2.6 on 2025-09-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='artistas/'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='ranking',
            field=models.FloatField(default=0),
        ),
    ]
