# Generated by Django 5.2.6 on 2025-09-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artistprofile_foto_artistprofile_ranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistprofile',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='sectors',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='apellido_grupo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='ciudad',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='pais',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='sectores',
            field=models.JSONField(default=list),
        ),
    ]
